name: publish
on:
  push:
    branches:
      - main
    paths:
      - 'packages/a/**'
      - '.github/workflows/publish.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/a/**'
      - '.github/workflows/publish.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    name: test npm run build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
      - run: npm run build --workspace packages/a
      - run: cd packages/a && npm run build

  deploy:
    name: Deploy worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
      - name: Publish worker
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'packages/a'

